name: catalog-api-cicd-appcfg

# trigger:
#   branches:
#     include:
#       - master
#   paths:
#     include:
#       - apps/catalog-api/*

trigger: none
pr: none

variables:
  dotnetSdkVersion: "6.x"
  buildConfiguration: Release
  releaseBranchName: master
  azSubscription: scFood
  folder: apps/catalog-api/api/
  appservice: catalog-api-mi-18760
  cfgEP: 'https://foodconfig-18760.azconfig.io'

####
# assign permissions to service connection pricipal on app config service

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CfgBuild
    jobs:    
      - job: CfgBuild
        displayName: "Replace Cfg and Build"

        steps:                
        
        - task: CmdLine@2
          displayName: Printing Env before
          inputs:
            script: |
                printenv

        - task: AzureAppConfiguration@5
          displayName: Read App Config
          inputs:
           azureSubscription: '$(azSubscription)'
           AppConfigurationEndpoint: '$(cfgEP)'
           KeyFilter: '*'
           Label: 'production'
        
        - task: CmdLine@2
          displayName: Printing Env after
          inputs:
            script: |
                printenv

        - task: CmdLine@2
          displayName: Printing Env after setting var
          inputs:
            script: |
                printenv

        - task: FileTransform@1
          displayName: Update Configuration
          inputs:
            folderPath: '$(System.DefaultWorkingDirectory)/apps/catalog-api/api/**/'
            fileType: 'json'
            targetFiles: '**/appsettings.json'
        
        - template: templates/t-net-build.yaml
          parameters:
            cfg: $(buildConfiguration)
            folder: $(folder)



  - stage: Deploy
    displayName: Deploy
    dependsOn: CfgBuild
    
    jobs:
      - deployment: DeployAppService
        displayName: Deploy to Appservice
        environment: SecureProd
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"                    

                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: $(appservice)"
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: $(azSubscription)
                    appType: "webApp"
                    WebAppName: $(appservice)
                    packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"